"""
CareerNest — Dynamic /config.js Endpoint

Reads all frontend config from environment variables and serves them
as a JavaScript file. This replaces the static config.js entirely —
no credentials ever need to be committed to the repo.

Environment variables read:
    GOOGLE_CLIENT_ID   — Google OAuth 2.0 client ID
    ADMIN_EMAILS       — comma-separated list of admin Gmail addresses
    API_BASE           — backend base URL (empty string = same origin)
"""
import os
import json
from fastapi import APIRouter
from fastapi.responses import Response

router = APIRouter(include_in_schema=False)


def _build_config_js() -> str:
    google_client_id = os.getenv("GOOGLE_CLIENT_ID", "")

    # ADMIN_EMAILS can be a comma-separated string: "a@b.com,c@d.com"
    admin_emails_raw = os.getenv("ADMIN_EMAILS", os.getenv("ADMIN_EMAIL", ""))
    admin_emails = [e.strip() for e in admin_emails_raw.split(",") if e.strip()]

    # API_BASE: empty string means same-origin (correct for HuggingFace Spaces)
    api_base = os.getenv("API_BASE", "")

    # Serialize to JSON so values are safely escaped for JS
    return f"""/* Auto-generated by CareerNest backend — do not edit manually */
const CONFIG = {{
  GOOGLE_CLIENT_ID: {json.dumps(google_client_id)},
  ADMIN_EMAILS:     {json.dumps(admin_emails)},
  API_BASE:         {json.dumps(api_base)},
}};
"""


@router.get("/config.js")
def serve_config_js():
    """Serve frontend config generated from server environment variables."""
    js = _build_config_js()
    return Response(
        content=js,
        media_type="application/javascript",
        headers={
            # Don't cache — if env vars change, clients should get the new values
            "Cache-Control": "no-store",
        },
    )